<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function myFindAll(){

        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('a')
            ->from($this->_entityName, 'a');

        $queryBuilder = $this->createQueryBuilder('a');

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }

    public function getAdvertWithCategories(array $categoryNames){
        
        $qb = $this
            ->createQueryBuilder('a')
            ->join('a.categories', 'c')
            ->addSelect('c');

        $qb->where($qb->expr()->in('c.name, $categoryName'));

        return $qb
            ->getQuery()
            ->getResult();

    }

    public function getApplicationWithAdvert($limit){



    }
}
