<?php

namespace OC\PlatformBundle\Repository;

/**
 * updatedAtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class updatedAtRepository extends \Doctrine\ORM\EntityRepository
{
}
